import React from "react";
import '../styles/globals.css'

export default function RootLayout({children,}: { children: React.ReactNode }) {
    return (
        <html>
        <head>
            <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />
            <title>Competitive Meditation</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/public/favicon.ico"/>
        </head>
        <body>{children}</body>
        </html>
    )
}
