import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Button} from "@mui/material";
import {useState} from "react";
// @ts-ignore
import jstat from "jstat";

export default function Home() {

    const [meditating, setMeditating] = useState(false);
    const [startTime, setStartTime] = useState<number>(0);
    const [resultTime, setResultTime] = useState<number | null>(null);
    const [resultPercentile, setResultPercentile] = useState<number | null>(null);

    const startMeditation = () => {
        setResultTime(null)
        setResultPercentile(null)
        setMeditating(true)
        setStartTime(+new Date())
    }

    const stopMeditation = () => {
        setMeditating(false)
        const endTime = +new Date()
        const timeDelta = Math.round((endTime - startTime)) / 1000
        setResultTime(timeDelta)
        setPercentile(timeDelta)
        setStartTime(0)
    }

    const setPercentile = (timeDelta: number) => {
        const timeProbability = jstat.normal(30, 4).pdf(timeDelta);
        const timePercentile = timeProbability * 100
        const timePercentileRounded = Math.round(timePercentile * 1000) / 100
        setResultPercentile(timePercentileRounded)
    }

  return (
    <div className={styles.container}>
      <Head>
        <title>Competitive Meditation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className={styles.main}>
            { !meditating ?
            <Button
                variant={"outlined"}
                size={"large"}
                onClick={() => startMeditation()}>Begin</Button>
            :
            <Button
                variant={"outlined"}
                size={"large"}
                color={"secondary"}
                onClick={() => stopMeditation()}>Done</Button>}

            <h2 style={{marginBottom: 0}}>{resultTime ? resultTime + "s" : ''}</h2>
            <h3 style={{marginTop: 0}}>{resultPercentile != null ? resultPercentile + "th percentile" : ''}</h3>
        </main>
    </div>
  )
}
